[platformio]
default_envs = esp32-8048S070C

[env:esp32-8048S070C]
platform = espressif32@6.13.0
board = esp32-8048S070C
framework = arduino
monitor_speed = 115200

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -D LV_CONF_PATH=${PROJECT_INCLUDE_DIR}/lv_conf.h

build_src_filter =
    +<*>
    -<touch_display_test.cpp>

lib_deps =
    lvgl/lvgl@9.2.2
    https://github.com/rzeldent/esp32-smartdisplay.git#327322c80430b9fedddc870f0de60dac03194ebd

[env:touch-display-check]
platform = espressif32@6.13.0
board = esp32-8048S070C
framework = arduino
monitor_speed = 115200

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -D LV_CONF_PATH=${PROJECT_INCLUDE_DIR}/lv_conf.h

build_src_filter =
    -<*>
    +<touch_display_test.cpp>
    +<board/runtime.cpp>

lib_deps =
    lvgl/lvgl@9.2.2
    https://github.com/rzeldent/esp32-smartdisplay.git#327322c80430b9fedddc870f0de60dac03194ebd
