#!/usr/bin/env python3
"""Generate editable weather pictograms as LVGL 9.2 RGB565A8 C++ assets."""

from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/app/weather_icon_assets.cpp"
PREVIEW = ROOT / "docs/images/weather_icons_preview.png"
KINDS = ("Clear", "PartlyCloudy", "Cloud", "Rain", "Snow", "Thunder", "Fog")
SIZES = (32, 56)
AA = 4
SUN = "#E99B21"
CLOUD = "#718B9B"
RAIN = "#2587BD"
SNOW = "#4F9AC4"


def optically_center(image: Image.Image) -> Image.Image:
    """Center visible pixels, not the transparent square that contains them."""
    bounds = image.getchannel("A").getbbox()
    if bounds is None:
        return image
    left, top, right, bottom = bounds
    offset_x = round(image.width / 2 - (left + right) / 2)
    offset_y = round(image.height / 2 - (top + bottom) / 2)
    centered = Image.new("RGBA", image.size, (0, 0, 0, 0))
    centered.alpha_composite(image, (offset_x, offset_y))
    centered_bounds = centered.getchannel("A").getbbox()
    assert centered_bounds is not None
    centered_left, centered_top, centered_right, centered_bottom = centered_bounds
    assert abs((centered_left + centered_right) / 2 - image.width / 2) <= 0.5
    assert abs((centered_top + centered_bottom) / 2 - image.height / 2) <= 0.5
    return centered


def icon(kind: str, size: int) -> Image.Image:
    canvas = Image.new("RGBA", (size * AA, size * AA), (0, 0, 0, 0))
    draw = ImageDraw.Draw(canvas)
    scale = size * AA / 64

    def p(value: float) -> int:
        return round(value * scale)

    def sun(x: int = 32, y: int = 32, radius: int = 12) -> None:
        draw.ellipse((p(x - radius), p(y - radius), p(x + radius), p(y + radius)), fill=SUN)
        for dx, dy in ((0, -1), (0, 1), (-1, 0), (1, 0),
                       (-0.7, -0.7), (0.7, -0.7), (-0.7, 0.7), (0.7, 0.7)):
            draw.line((p(x + dx * (radius + 4)), p(y + dy * (radius + 4)),
                       p(x + dx * (radius + 10)), p(y + dy * (radius + 10))),
                      fill=SUN, width=max(1, p(3)))

    def cloud(y: int = 34) -> None:
        draw.ellipse((p(10), p(y - 8), p(34), p(y + 10)), fill=CLOUD)
        draw.ellipse((p(20), p(y - 16), p(48), p(y + 11)), fill=CLOUD)
        draw.ellipse((p(37), p(y - 7), p(56), p(y + 11)), fill=CLOUD)
        draw.rounded_rectangle((p(10), p(y), p(56), p(y + 12)), radius=p(6), fill=CLOUD)

    if kind == "Clear":
        sun()
    elif kind == "PartlyCloudy":
        sun(22, 22, 9)
        cloud(34)
    elif kind == "Fog":
        for x1, x2, y in ((13, 51, 21), (9, 55, 32), (15, 49, 43)):
            draw.rounded_rectangle((p(x1), p(y), p(x2), p(y + 5)),
                                   radius=p(2), fill=CLOUD)
    else:
        cloud(27 if kind in ("Rain", "Snow", "Thunder") else 34)
        if kind == "Rain":
            for x in (21, 32, 43):
                draw.line((p(x + 3), p(46), p(x), p(57)), fill=RAIN, width=max(1, p(4)))
        elif kind == "Snow":
            for x in (21, 32, 43):
                draw.line((p(x - 3), p(51), p(x + 3), p(51)), fill=SNOW, width=max(1, p(2)))
                draw.line((p(x), p(48), p(x), p(54)), fill=SNOW, width=max(1, p(2)))
        elif kind == "Thunder":
            draw.polygon([(p(35), p(43)), (p(25), p(52)), (p(33), p(52)),
                          (p(28), p(61)), (p(43), p(49)), (p(35), p(49)),
                          (p(40), p(43))], fill=SUN)

    return optically_center(canvas.resize((size, size), Image.Resampling.LANCZOS))


def rgb565a8_data(image: Image.Image) -> bytes:
    color = bytearray()
    alpha = bytearray()
    rgba = image.tobytes()
    for offset in range(0, len(rgba), 4):
        red, green, blue, opacity = rgba[offset:offset + 4]
        pixel = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        color.extend((pixel & 0xFF, pixel >> 8))
        alpha.append(opacity)
    return bytes(color + alpha)


def emit_array(name: str, data: bytes) -> str:
    lines = [f"alignas(4) static const std::uint8_t {name}[] = {{"]
    for offset in range(0, len(data), 16):
        row = ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16])
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    lines = [
        '// Generated by tools/generate_weather_icon_assets.py. Edit that script, then regenerate.',
        '#include "app/weather_icon_assets.hpp"',
        '',
        'namespace calendar::weather_icon::assets {',
        'namespace {',
        'constexpr lv_image_dsc_t descriptor(const std::uint8_t* data,',
        '                                     std::uint16_t size, std::uint32_t bytes) {',
        '    lv_image_dsc_t image{};',
        '    image.header.magic = LV_IMAGE_HEADER_MAGIC;',
        '    image.header.cf = LV_COLOR_FORMAT_RGB565A8;',
        '    image.header.w = size;',
        '    image.header.h = size;',
        '    image.header.stride = size * 2;',
        '    image.data_size = bytes;',
        '    image.data = data;',
        '    return image;',
        '}',
        '',
    ]
    preview = Image.new("RGB", (7 * 84, 2 * 92), "#f2f5f7")
    preview_draw = ImageDraw.Draw(preview)
    for row, size in enumerate(SIZES):
        for column, kind in enumerate(KINDS):
            image = icon(kind, size)
            data = rgb565a8_data(image)
            assert len(data) == size * size * 3
            assert image.getchannel("A").getextrema()[1] == 255
            array_name = f"k{kind}{size}Data"
            desc_name = f"k{kind}{size}"
            lines.append(emit_array(array_name, data))
            lines.append(f"const lv_image_dsc_t {desc_name} = "
                         f"descriptor({array_name}, {size}, sizeof({array_name}));")
            lines.append("")
            preview.paste(image, (column * 84 + (84 - size) // 2, row * 92 + 4), image)
            preview_draw.text((column * 84 + 5, row * 92 + 68), kind, fill="#15384d")
    lines.extend((
        '}  // namespace',
        '',
        'const lv_image_dsc_t* get(Kind kind, bool large) {',
        '    switch (kind) {',
    ))
    for kind in KINDS:
        lines.append(f"        case Kind::{kind}: return large ? &k{kind}56 : &k{kind}32;")
    lines.extend((
        '    }',
        '    return large ? &kCloud56 : &kCloud32;',
        '}',
        '',
        '}  // namespace calendar::weather_icon::assets',
    ))
    OUTPUT.write_text("\n".join(lines) + "\n")
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)


if __name__ == "__main__":
    main()
